name: Deploy to Github Pages
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Use Node.JS 
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Cache pnpm modules
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-

    - name: Install dependencies
      uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.21.0
        run_install: |
          - recursive: true
            args: [--frozen-lockfile]

    - name: Build
      run: |
        npm run deploy

    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: dist
        GITHUB_TOKEN: ${{ secrets.GH_DEPLOY_TOKEN }}
